### ISSUE TITLE
Где взять дистрибутив site-discovery-flea?

### ISSUE THREAD

**Issue by ttsrg** [lebe-dev/vhost-discovery-tool#1]
ПРиветствую, а где собственно сам файл? )

**Comment by lebe-dev** [comment]
Добрый день

в релизах:
https://github.com/lebe-dev/site-discovery-flea/releases

**Comment by ttsrg** [comment]
Cори за мою недальнозоркость. Спасибо за труды.

В 5-й забикс импортировался темплейт без проблем, но не заработал. Есть неудобства вида жесткой привязки к определенным каталогам:
/var/lib/zabbix 
/etc/nginx/conf.d 

 на моем опыте такие пути  чаще встречаются:
 /etc/zabbix/ (/etc/zabbix/zabbix_agentd.d) и
 /etc/nginx/sites-enabled/

возможно ли как то "флею" в баш "перекомпилить"?

**Comment by lebe-dev** [comment]
сделаю сегодня:

1. дефолтный рабочий каталог `/etc/zabbix`
2. возможность переопределить рабочий каталог опцией
3. возможность указать root путь для конфигов nginx опцией

> возможно ли как то "флею" в баш "перекомпилить"?

неа, я думаю полно умельцев которые реализовали эту функциональность простынями на bash :) тут на гитхабе, лоре или форумах заббикса.

**Comment by lebe-dev** [comment]
Изменения доступны в версии 1.1.0:
https://github.com/lebe-dev/site-discovery-flea/releases
