### ISSUE TITLE
only .conf files are detected

### ISSUE THREAD

**Issue by bbx-github** [lebe-dev/vhost-discovery-tool#20]
For some reason only the first 50 vhosts are recognized. If I turn on debug logging, I can also see that one of the first messages `DEBUG - vhost files collected:` only contain the first 50 vhosts. 

I did not customize anything, all the configuration was done like it was documented. Everything else works as it should. I am running Debian 11.7 with nginx. No Errors or anything, it just only works for the first 50 entries.

**Comment by lebe-dev** [comment]
Thanks for report. I'll check it.

**Comment by lebe-dev** [comment]
Could you provide screenshot with full path to configs and file listing? You can blur sensitive information It doesn't matter for investigation.

App looking for config files here `/etc/nginx/conf.d` in default configuration. Each config should have file extension `.conf`.

**Comment by bbx-github** [comment]
Oh no. The files are only sometimes named *.conf, most of them are *.vhost. So it is not an issue with the number. I was just misled because `50` felt strange.

Is there a possibility to change the postfix the app is looking for?

**Comment by lebe-dev** [comment]
I've added an option `--file-extensions` and you can specify extensions separated by comma:

```shell
--file-extensions=.conf,.vhost
```

Default value is `.conf,.vhost`

https://github.com/lebe-dev/vhost-discovery-tool/releases/tag/1.5.4

**Comment by bbx-github** [comment]
Thank you! But can you build a static binary as well? I have no rhel system I could test it with.

**Comment by lebe-dev** [comment]
Sure

https://github.com/lebe-dev/vhost-discovery-tool/releases/download/1.5.4/vhdt-v1.5.4-linux-static.zip

**Comment by bbx-github** [comment]
Ok, it runs now, but throws me this weird error about a missing apache vhost path. I dont have apache running.

```
sudo -u zabbix RUST_BACKTRACE=full /usr/bin/vhdt --nginx-vhosts-path=/etc/nginx/sites-enabled/ --log-level=debug
thread 'main' panicked at src/main.rs:179:10:
couldn't get vhosts from apache: vhosts path doesn't exist
stack backtrace:
   0:     0x7f5b1a974abe - <unknown>
   1:     0x7f5b1a8d01dc - <unknown>
   2:     0x7f5b1a951ced - <unknown>
   3:     0x7f5b1a97b618 - <unknown>
   4:     0x7f5b1a97b3b2 - <unknown>
   5:     0x7f5b1a97bad3 - <unknown>
   6:     0x7f5b1a97b7b2 - <unknown>
   7:     0x7f5b1a97b716 - <unknown>
   8:     0x7f5b1a97b701 - <unknown>
   9:     0x7f5b1a873b62 - <unknown>
  10:     0x7f5b1a873f59 - <unknown>
  11:     0x7f5b1a87c89c - <unknown>
  12:     0x7f5b1a8831ea - <unknown>
  13:     0x7f5b1a87b204 - <unknown>
  14:     0x7f5b1a8850f3 - <unknown>
  15:     0x7f5b1a97d59a - <unknown>
  16:     0x7f5b1a97f43d - <unknown>
  17:     0x7f5b1a879575 - <unknown>
  18:                0x0 - <unknown>
Aborted
```

**Comment by lebe-dev** [comment]
Let me check :)

**Comment by lebe-dev** [comment]
App won't crash if the vhost path doesn't exist. It just logs the info and keeps going

https://github.com/lebe-dev/vhost-discovery-tool/releases/download/1.5.4/vhdt-v1.5.4-preview-3-linux-static.zip

**Comment by bbx-github** [comment]
Thank you very much for all your work! it works now :)
