### ISSUE TITLE
Dont panic when individual files are not accessible

### ISSUE THREAD

**Issue by bbx-github** [lebe-dev/vhost-discovery-tool#22]
When a single vhost config is for whatever reason not read accessible the whole program fails with:

```
thread 'main' panicked at src/main.rs:166:10:
couldn't get vhosts from nginx: couldn't get virtual hosts from file

Caused by:
    Permission denied (os error 13)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

The fact that a single file is not accessible is not a good enough reason to completely stop the program and output this error code. It would be better to catch the error and output a log message for example. 

This is happening with the latest 1.5.4 release.

**Comment by lebe-dev** [comment]
Thanks for report. I've changed default behavior. It doesn't fall on parse errors by default.
Preview version:

https://github.com/lebe-dev/vhost-discovery-tool/releases/download/1.5.4/vhdt-v1.5.4-preview-2-linux-static.zip

**Comment by bbx-github** [comment]
Tested it, it works thank you!
